# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: 'ba0a9e79-9926-4d93-a646-2298e8f469b8'

  # Web app name
  webAppName: 'python-cicd-23737'

  # Agent VM image name
  name: 'SelfAgent1'

  # Environment name
  environmentName: 'python-cicd-23737'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  # Python version: 3.7
  pythonVersion: '3.8'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      name: 'SelfAgent1'
    steps:

    - script: |
        python3 -m venv antenv
        source antenv/bin/activate
        python3 -m pip install --upgrade pip
        pip install setup
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: "Install requirements"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop
    - script: |
        pip3 install setup
        pip3 install -r $(projectRoot)/requirements.txt
        pip3 install pytest
        python3 -m pytest Tests/unit_tests --junitxml=$(System.DefaultWorkingDirectory)/TestResults/test-results-unit.xml
        pip3 install pycmd
      displayName: 'Run unit tests'
    - task: PublishTestResults@2
      inputs:        
        searchFolder: $(System.DefaultWorkingDirectory)
        testResultsFiles: '**/test-*.xml'
      displayName: 'Publish test results'
    - publish: $(System.DefaultWorkingDirectory)/Tests
      artifact: tests
- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      name: $(name)
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:



          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : python-cicd-23737'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip